### PR TITLE
多核el2启动、gic相关

### PR DESCRIPTION
**Pull request by pengzechen**

### CODE REVIEW

**Comment by hky1999** [comment]
Please submit your modifications to the [arm-gicv2](https://github.com/arceos-org/arm_gicv2/) crate.

Then update the dep url in ArceOS

**Comment by hky1999** [comment]
I believe that commits including "2 cpu" and "shell" is not ready to be merged.

**Comment by hky1999** [comment]
Use English in your commit msg next time.

**Comment by pengzechen** [comment]
> I believe that commits including "2 cpu" and "shell" is not ready to be merged.

yes, I know this.

> Please submit your modifications to the [arm-gicv2](https://github.com/arceos-org/arm_gicv2/) crate.

ok

**Pull request closed without merging**
