### PR TITLE
[refactor] aarch64 el2 support

### PR DESCRIPTION
**Pull request by hky1999**

### CODE REVIEW

**Review by aarkegz — DISMISSED** [review]
LGTM

**Comment by hky1999** [comment]
the reason I seperate `boot_el2.rs`

I hope we can perform switch_to_el2 operation in [arm_vcpu](https://github.com/arceos-hypervisor/arm_vcpu/), while leave arceos's runtime environment as it is.

**Comment by aarkegz** [comment]
> the reason I seperate `boot_el2.rs`
> 
> I hope we can perform switch_to_el2 operation in [arm_vcpu](https://github.com/arceos-hypervisor/arm_vcpu/), while leave arceos's runtime environment as it is.

It sounds good and sensible. However, will it require more modifications in ArceOS?

**Comment by aarkegz** [comment]
> the reason I seperate `boot_el2.rs`
> 
> I hope we can perform switch_to_el2 operation in [arm_vcpu](https://github.com/arceos-hypervisor/arm_vcpu/), while leave arceos's runtime environment as it is.

Maybe you can first create a feature issue in this repo?

**Comment by hky1999** [comment]
> > the reason I seperate `boot_el2.rs`
> > I hope we can perform switch_to_el2 operation in [arm_vcpu](https://github.com/arceos-hypervisor/arm_vcpu/), while leave arceos's runtime environment as it is.
> 
> It sounds good and sensible. However, will it require more modifications in ArceOS?

I do not want any modification in ArceOS's platform.

some mechanism can refer to Jailhouse, something related to switch from ArceOS at el1 into arm_vcpu at el2, after that each exception should be caught by arm_vcpu and dispatch to ArceOS of needed

**Comment by aarkegz** [comment]
> I do not want any modification in ArceOS's platform.

That's right.

> some mechanism can refer to Jailhouse, something related to switch from ArceOS at el1 into arm_vcpu at el2, after that each exception should be caught by arm_vcpu and dispatch to ArceOS of needed

It makes sense.

**Review by aarkegz — APPROVED** [review]
LGGTM

**Pull request merged**
